<?php namespace App\Entities\Finance;

use App\Entities\BaseEntity;

class Account extends BaseEntity
{
    public $account_id; // bigint DEFAULT nextval(('"account_account_id_seq"'::text)::regclass) NOT NULL,
    public $account; // character varying(50) NOT NULL,
    public $account_status; // character(1),
    public $address; // character varying(100),
    public $telno; // character varying(20),
    public $ofc_telno; // character varying(20),
    public $office; // character varying(50),
    public $ofc_address; // character varying(100),
    public $remarks; // text,
    public $audit; // text,
    public $account_code; // character varying(10),
    public $account_group_id; // integer,
    public $comaker1; // character varying(40),
    public $comaker1_address; // character varying(50),
    public $comaker2; // character varying(40),
    public $comaker2_address; // character varying(50),
    public $comaker1_relation; // character varying,
    public $comaker2_relation; //  character varying,
    public $income; // numeric(10,2),
    public $civil_status; // character(1),
    public $collection_type_id; // integer,
    public $bank_account; // character varying(15),
    public $salary; //  numeric(10,2),
    public $sss; //  character varying(30),
    public $pix; //  character varying,
    public $clientbank_id; //  integer,
    public $bank_pin; //  character varying(10),
    public $branch_id; //  integer,
    public $withdraw_day; //  smallint,
    public $date_atm_in; //  character varying(15),
    public $date_atm_out; //  character varying(15),
    public $bank_cardno; //  character varying(20),
    public $date_birth; //  character varying,
    public $gender; //  character(1),
    public $age; //  character varying,
    public $mclass; //  character(1),
    public $date_child21; //  text,
    public $npension; //  smallint,
    public $nchangebank; //  smallint,
    public $spouse; //  character varying,
    public $spouse_sss; //  character varying,
    public $smartno; //  character varying,
    public $current_day; //  smallint,
    public $pensionpin; //  character varying,
    public $regdate; //  date,
    public $mactivate; //  character varying,
    public $date_child21b; //  text,
    public $date_child21c; //  text,
    public $date_child21d; //  text,
    public $ecamount; //  numeric(10,2),
    public $member; //  character varying,
    public $disability; //  numeric(10,2),
    public $child1; //  character varying,
    public $child2 ; // character varying,
    public $child3; //  character varying,
    public $child4; //  character varying,
    public $wday; //  smallint,
    public $firstname; //  character varying,
    public $lastname; //  character varying,
    public $middlename; //  character varying
}